import Head from "next/head"
import Script from "next/script"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col bg-gradient-to-b from-gray-900 to-slate-800 text-white">
        <header className="py-16">
          <h1 className="mb-6 text-center text-5xl font-bold">
            Create Tailwind
          </h1>
          <div className="flex flex-row items-center justify-center gap-4">
            <a
              className="github-button"
              href="https://github.com/andrejjurkin/create-tailwind-app"
              data-color-scheme="no-preference: dark; light: dark; dark: dark;"
              data-icon="octicon-star"
              data-size="large"
              rel="noreferrer"
              data-show-count="true"
              aria-label="Star andrejjurkin/create-tailwind-app on GitHub"
            >
              Star
            </a>
            <a
              className="github-button"
              href="https://github.com/andrejjurkin/create-tailwind-app/discussions"
              data-color-scheme="no-preference: dark; light: dark; dark: dark;"
              data-icon="octicon-comment-discussion"
              data-size="large"
              aria-label="Discuss andrejjurkin/create-tailwind-app on GitHub"
            >
              Discuss
            </a>
          </div>
        </header>

        <main className="flex-1">
          <section className="text-center">
            <h2 className="text-center text-3xl font-medium">
              Next.js Project Created using{" "}
              <a
                href="https://nextjs.org/docs/api-reference/create-next-app"
                target="_blank"
                className="text-indigo-300"
                rel="noreferrer"
              >
                create-next-app
              </a>
            </h2>
            <p className="mb-6">
              Officially maintained by the creators of Next.js
            </p>
          </section>
        </main>

        <footer className="border-t border-gray-800 px-8 py-12">
          <div className="px-8 text-center font-medium">
            <a href="https://github.com/andrejjurkin/create-tailwind-app">
              Create Tailwind
            </a>
          </div>
        </footer>
      </div>
      <Script src="https://buttons.github.io/buttons.js" />
    </div>
  )
}
